// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MvcProducts.Models;
using System;

namespace Unique.Migrations
{
    [DbContext(typeof(MvcProductsContext))]
    [Migration("20180726100730_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcEkkremotites.Models.cEkkremotites", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ekkremotites");

                    b.Property<string>("Location");

                    b.HasKey("ID");

                    b.ToTable("cEkkremotites");
                });

            modelBuilder.Entity("MvcKostologisi.Models.Kostologisi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("ChargeExtra");

                    b.Property<string>("ChargeMethod");

                    b.Property<float>("ChargeWork");

                    b.Property<float?>("FPA");

                    b.Property<string>("Location");

                    b.Property<float?>("Total");

                    b.HasKey("ID");

                    b.ToTable("Kostologisi");
                });

            modelBuilder.Entity("MvcProducts.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("ChargeExtra");

                    b.Property<string>("ChargeMethod");

                    b.Property<float>("ChargeWork");

                    b.Property<string>("Description");

                    b.Property<string>("Ekkremotites");

                    b.Property<string>("ErgasiaTexnikou");

                    b.Property<string>("ExtraNotes");

                    b.Property<string>("ExtraParts");

                    b.Property<float?>("FPA");

                    b.Property<DateTime?>("FixDate");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<int?>("Number");

                    b.Property<string>("Phone");

                    b.Property<string>("Products");

                    b.Property<string>("Promitheftes");

                    b.Property<DateTime?>("ReceiveDate");

                    b.Property<string>("Send");

                    b.Property<float?>("Total");

                    b.Property<string>("UsedExtra");

                    b.HasKey("ID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("MvcPromitheftes.Models.cPromitheftes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location");

                    b.Property<string>("Promitheftes");

                    b.HasKey("ID");

                    b.ToTable("cPromitheftes");
                });

            modelBuilder.Entity("MvcProsEpiskevi.Models.cProsEpiskevi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("FixDate");

                    b.Property<string>("Location");

                    b.HasKey("ID");

                    b.ToTable("cProsEpiskevi");
                });

            modelBuilder.Entity("MvcProsthikiArithmouDeltiou.Models.ProsthikiArithmouDeltiou", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location");

                    b.Property<int>("Number");

                    b.HasKey("ID");

                    b.ToTable("ProsthikiArithmouDeltiou");
                });
#pragma warning restore 612, 618
        }
    }
}
